"""Write JSON Schema files for the protocol models."""

from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel

from golem_protocol.commands import DaemonStatus, HelloParams, HelloResult, PingParams
from golem_protocol.events import Ping
from golem_protocol.rpc import RpcErrorBody, RpcFailure, RpcRequest, RpcSuccess
from golem_protocol.version import PROTOCOL_MAJOR, PROTOCOL_MINOR

MODELS: tuple[type[BaseModel], ...] = (
    Ping,
    PingParams,
    HelloParams,
    HelloResult,
    DaemonStatus,
    RpcRequest,
    RpcErrorBody,
    RpcSuccess,
    RpcFailure,
)


def schema_stem(name: str) -> str:
    """Turn ``MessageDelta`` into ``message-delta``."""
    chars: list[str] = []
    for char in name:
        if char.isupper() and chars:
            chars.append("-")
        chars.append(char.lower())
    return "".join(chars)


def default_gen_dir() -> Path:
    """``packages/protocol/gen``, derived from this source file."""
    return Path(__file__).resolve().parent.parent / "gen"


def export_schemas(directory: Path) -> list[Path]:
    """Write one JSON Schema file per protocol model. Returns the paths written."""
    directory.mkdir(parents=True, exist_ok=True)
    for stale in directory.glob("*.schema.json"):
        stale.unlink()
    written: list[Path] = []
    for model in MODELS:
        schema = model.model_json_schema()
        path = directory / f"{schema_stem(model.__name__)}.schema.json"
        path.write_text(
            json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        written.append(path)
    return written


def export_version(directory: Path) -> Path:
    """Write ``version.ts`` from :mod:`golem_protocol.version`.

    ``just gen`` deletes ``*.ts`` before json2ts runs, then calls this so the
    constants are regenerated with the schemas.
    """
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "version.ts"
    path.write_text(
        "/* Generated by `just gen` from golem_protocol.version. Do not edit. */\n"
        "\n"
        f"export const PROTOCOL_MAJOR = {PROTOCOL_MAJOR};\n"
        f"export const PROTOCOL_MINOR = {PROTOCOL_MINOR};\n",
        encoding="utf-8",
    )
    return path


def main() -> None:
    export_schemas(default_gen_dir())


if __name__ == "__main__":
    main()
