# Golem development tasks. `just` lists them.
# Recipes drop an inherited VIRTUAL_ENV so uv uses this repository's `.venv`.

set shell := ["env", "-u", "VIRTUAL_ENV", "bash", "-cu"]

# List recipes.
[private]
default:
    @just --list

# Export protocol JSON Schema and generate TypeScript from it.
gen:
    #!/usr/bin/env bash
    set -euo pipefail
    unset VIRTUAL_ENV
    uv run python -m golem_protocol.codegen
    rm -f packages/protocol/gen/*.ts
    for schema in packages/protocol/gen/*.schema.json; do
      stem="$(basename "$schema" .schema.json)"
      pnpm exec json2ts \
        --input "$schema" \
        --output "packages/protocol/gen/${stem}.ts" \
        --style.singleQuote \
        --unreachableDefinitions \
        --bannerComment '/* Generated by `just gen` from golem_protocol models. Do not edit. */'
    done
    uv run python -c 'from golem_protocol.codegen import default_gen_dir, export_version; export_version(default_gen_dir())'

# Lint Python and the TypeScript packages.
lint:
    uv run ruff check packages
    uv run ruff format --check packages
    pnpm -r --if-present lint

# Format Python.
fmt:
    uv run ruff format packages
    uv run ruff check --fix packages

# Typecheck Python (strict) and the TypeScript packages.
typecheck:
    uv run pyright
    pnpm -r --if-present typecheck

# Run tests.
test:
    uv run pytest
    pnpm -r --if-present test

# Run the golem CLI (status, daemon install|start|stop|logs).
golem *args:
    pnpm exec golem {{args}}

# Open the status TUI.
tui:
    pnpm --filter @golem/tui start

# Lint, typecheck, test, and fail if generated protocol files drift.
check:
    #!/usr/bin/env bash
    set -euo pipefail
    unset VIRTUAL_ENV
    snapshot="$(mktemp -d)"
    trap 'rm -rf "$snapshot"' EXIT
    mkdir -p packages/protocol/gen
    cp -R packages/protocol/gen/. "$snapshot/"
    just gen
    if ! diff -ru "$snapshot" packages/protocol/gen; then
      printf 'packages/protocol/gen drifted from the protocol models. Commit the regenerated files.\n' >&2
      exit 1
    fi
    just lint
    just typecheck
    just test
